Create user
trantuanngoc/exam_management pull request #12
Opened 2020-09-01 02:40 UTC by trantuanngoc

2020-09-01 03:06 UTC, n299 commented on app/views/users/shared/_links.html.erb
> +<%- if controller_name != 'sessions' %>
remove

2020-09-01 03:06 UTC, n299 commented on db/migrate/20200824063959_create_users.rb
>  class CreateUsers < ActiveRecord::Migration[6.0]
tạo migration mới, ko chỉnh sửa file cũ

2020-09-01 03:06 UTC, n299 commented on yarn.lock
>    resolved "https://registry.yarnpkg.com/boolbase/-/boolbase-1.0.0.tgz#68dff5fbe60c51eb37725ea9e3ed310dcc1e776e"
gitignore

2020-09-01 04:14 UTC, trantuanngoc commented on app/views/layouts/application.html.erb
> +      <% flash.each do |message_type, message| %>
comment nhầm à, đằng dưới chứ

2020-09-01 04:43 UTC, trantuanngoc commented on app/views/users/shared/_links.html.erb
> +<%- if controller_name != 'sessions' %>
devise gem code, not mine

2020-09-01 07:37 UTC, n299 commented on app/views/static_pages/home.html.erb
> +
remove empty line

2020-09-01 07:37 UTC, n299 commented on app/views/users/registrations/edit.html.erb
> +
remove empty line

2020-09-01 07:45 UTC, n299 commented on app/controllers/profiles_controller.rb
> +  def show
def show; end

2020-09-01 07:45 UTC, n299 commented on app/controllers/users/sessions_controller.rb
> +  # before_action :configure_sign_in_params, only: [:create]
remove comments

2020-09-01 07:55 UTC, n299 commented
LGTM! @trantuanngoc

2020-09-01 10:07 UTC, vuhuutuan123 commented on app/controllers/users/registrations_controller.rb
> +class Users::RegistrationsController < Devise::RegistrationsController
remove

2020-09-01 10:16 UTC, vuhuutuan123 requested changes

2020-09-01 10:16 UTC, vuhuutuan123 commented on app/controllers/users/sessions_controller.rb
> +  def destroy
after_sign_out

2020-09-01 10:16 UTC, vuhuutuan123 commented on app/helpers/profiles_helper.rb
> +  def gravatar_for(user)
default img url

2020-09-01 10:16 UTC, vuhuutuan123 commented on app/views/layouts/_header.html.erb
> +              <li><%= link_to "Profile", user_profile_path(current_user) %></li>
why pass argument current_user

2020-09-01 10:16 UTC, vuhuutuan123 commented on app/controllers/profiles_controller.rb
> +    @user = User.find_by(id: params[:user_id])
current_user

2020-09-01 10:16 UTC, vuhuutuan123 commented on app/views/users/shared/_links.html.erb
> +<%- if controller_name != 'sessions' %>
remove

2020-09-01 10:56 UTC, trantuanngoc commented on app/controllers/users/registrations_controller.rb
> +class Users::RegistrationsController < Devise::RegistrationsController
Cái này có tác dụng để render ra view edit.html.erb để chỉnh sửa password và email của user ạ

2020-09-03 08:09 UTC, trantuanngoc commented on app/views/layouts/_header.html.erb
> +              <li><%= link_to "Profile", user_profile_path(current_user) %></li>
Em dùng 
resources :users do
    resource :profile
end
nên nó không mặc định truyền user_id của current_user cho user_profile_path được

2020-09-03 10:25 UTC, vuhuutuan123 requested changes

2020-09-03 10:25 UTC, vuhuutuan123 commented on app/controllers/profiles_controller.rb
> +    unless current_user == User.find_by(id: params[:user_id])
remove

2020-09-03 10:25 UTC, vuhuutuan123 commented on app/controllers/users/sessions_controller.rb
> +    def after_sign_out_path_for(resource)
_resource

2020-09-03 10:25 UTC, vuhuutuan123 commented on app/views/layouts/_header.html.erb
> +              <li><%= link_to "Profile", user_profile_path(current_user) %></li>
remove

2020-09-03 11:04 UTC, vuhuutuan123 approved these changes
LGTM

2020-09-03 11:12 UTC, merged